"""add_preferred_time_to_tasks

Revision ID: 769a86cd48cc
Revises: 516b6f4f9866
Create Date: 2025-07-28 12:42:21.234487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769a86cd48cc'
down_revision: Union[str, Sequence[str], None] = '516b6f4f9866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('preferred_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'preferred_time')
    # ### end Alembic commands ###
