"""remove task categories

Revision ID: a1a52b2b8e31
Revises: ee7acce54ad1
Create Date: 2025-08-13 19:57:56.794201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1a52b2b8e31'
down_revision: Union[str, Sequence[str], None] = 'ee7acce54ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('category', postgresql.ENUM('work', 'personal', 'health', name='taskcategory'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
