"""make mood_type and intensity optional

Revision ID: df0a28ecae0c
Revises: 04c2625a6602
Create Date: 2025-07-27 16:36:43.250260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df0a28ecae0c'
down_revision: Union[str, Sequence[str], None] = '04c2625a6602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moods', 'mood_type',
               existing_type=postgresql.ENUM('happy', 'sad', 'anxious', 'angry', 'neutral', 'tired', 'stressed', 'depressed', name='moodtype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moods', 'mood_type',
               existing_type=postgresql.ENUM('happy', 'sad', 'anxious', 'angry', 'neutral', 'tired', 'stressed', 'depressed', name='moodtype'),
               nullable=False)
    # ### end Alembic commands ###
