"""added calendar id field to tasks table

Revision ID: ee7acce54ad1
Revises: 769a86cd48cc
Create Date: 2025-08-11 21:59:21.662506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7acce54ad1'
down_revision: Union[str, Sequence[str], None] = '769a86cd48cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('calendar_event_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'calendar_event_id')
    # ### end Alembic commands ###
